[tox]
requires =
    tox>=4.2
env_list =
    lint
    py{313, 312, 311}-d{52, 42, 32}
envlogdir = {toxinidir}/build/{envname}/log
envtmpdir = {toxinidir}/build/{envname}/tmp

[testenv]
deps =
    d32: django==3.2.*
    d42: django==4.2.*
    d51: django==5.2.*
extras =
    test
pass_env =
    PYTHONDONTWRITEBYTECODE
    PYTHONPATH
    USER
set_env =
    PYTHONDONTWRITEBYTECODE = true
commands =
    ruff check -e
    ruff format --check
    pytest tests \
      -q \
      --create-db \
      --cov-config={toxinidir}/tests/.coveragerc \
      --cov=unicef_security
allowlist_externals =
    flake8
    pytest
    ruff

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
pass_env =
    HOMEPATH
    PROGRAMDATA
commands =
    pre-commit run --all-files --show-diff-on-failure
