# Generated by Django 2.1.5 on 2019-02-01 19:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import django_countries.fields

import unicef_security.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('long_name', models.CharField(max_length=150, verbose_name='long name')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'swappable': 'BUSINESSAREA_MODEL',
            },
            bases=(models.Model, unicef_security.models.TimeStampedModel),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
            bases=(models.Model, unicef_security.models.TimeStampedModel),
        ),
        migrations.AddField(
            model_name='businessarea',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicef_security.Region'),
        ),
    ]
