# Generated by Django 3.2.10 on 2022-02-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_security', '0002_auto_20201028_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessarea',
            name='last_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='region',
            name='last_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
